const now = new Date().toISOString();
export const DEMO_ADS: any[] = [
  { id: 'demo-1', title: 'مزهرية عثمانية نحاسية مطعّمة بالفضة', price_egp: 4500, category: 'antiques', subcategory: 'مزهريات', location: 'القاهرة', package: 'premium', photos: [], description: 'مزهرية نحاسية من أواخر العهد العثماني، مطعّمة بخيوط الفضة بزخارف نباتية دقيقة. الارتفاع 34 سم، الحالة ممتازة بدون كسور أو لحام، وعليها طبقة أكسدة طبيعية تدل على العمر. مناسبة لهواة جمع النحاسيات وللديكور الكلاسيكي.', seller_phone: '01029397797', status: 'approved', created_at: now, view_count: 120 },
  { id: 'demo-2', title: 'ساعة حائط فرنسية 1920 تعمل بالمفتاح', price_egp: 7800, category: 'watches-jewelry', subcategory: 'ساعات كلاسيكية', location: 'الإسكندرية', package: 'featured', photos: [], description: 'ساعة حائط فرنسية من عشرينيات القرن الماضي بصندوق خشب جوز وميناء بورسلين بأرقام رومانية. تعمل بالمفتاح الأصلي المرفق، الدقات سليمة والحركة مضبوطة. القطر 42 سم.', seller_phone: '01029397797', status: 'approved', created_at: now, view_count: 88 },
  { id: 'demo-3', title: 'جراموفون بالبوق النحاسي بحالة عمل ممتازة', price_egp: 15000, category: 'vintage-electronics', subcategory: 'جراموفون', location: 'الجيزة', package: 'special', photos: [], description: 'جراموفون كلاسيكي ببوق نحاسي مصقول وصندوق خشبي أصلي، يعمل بالتدوير اليدوي ويشغّل أسطوانات 78 لفة بصوت نقي. قطعة عرض نادرة لهواة المقتنيات والمقاهي الكلاسيكية.', seller_phone: '01029397797', status: 'approved', created_at: now, view_count: 210 },
  { id: 'demo-4', title: 'طقم أنتريه لويس كامل خشب زان بحفر يدوي', price_egp: 32000, category: 'classic-furniture', subcategory: 'لويس', location: 'القليوبية', package: 'basic', photos: [], description: 'أنتريه لويس كامل من خشب الزان الأحمر بحفر يدوي وتذهيب، مكوّن من كنبة وأربعة كراسي وترابيزة وسط. القماش مجدد بالكامل بقطيفة فرنسية. الهيكل سليم تماماً بدون نمل أو تسوس.', seller_phone: '01029397797', status: 'approved', created_at: now, view_count: 45 },
  { id: 'demo-5', title: 'مجموعة عملات ملكية مصرية نادرة 12 قطعة', price_egp: 2600, category: 'books-docs', subcategory: 'عملات', location: 'المنصورة', package: 'basic', photos: [], description: 'مجموعة من 12 عملة معدنية من العهد الملكي المصري تشمل قروش الملك فؤاد والملك فاروق بفئات مختلفة. الحالة من جيدة جداً إلى ممتازة، محفوظة في ألبوم واقٍ.', seller_phone: '01029397797', status: 'approved', created_at: now, view_count: 67 },
  { id: 'demo-6', title: 'سجادة شرقية يدوية صوف طبيعي 3×2 متر', price_egp: 9500, category: 'art-decor', subcategory: 'سجاد شرقي', location: 'الغربية', package: 'special', photos: [], description: 'سجادة شرقية منسوجة يدوياً من الصوف الطبيعي بصبغات نباتية، نقشة ميدالية مركزية بألوان عنابي وكحلي وذهبي. المقاس 3×2 متر، الوبر كامل والأطراف سليمة.', seller_phone: '01029397797', status: 'approved', created_at: now, view_count: 30 },
];
